### ISSUE TITLE
The source code

### ISSUE THREAD

**Issue by Xinchungeorb** [iksoolim/asymmetric_N-player_trust_game#1]
Thanks for your paper! I saw your paper in IEEE XPLORE. May I know when the source code will be available to the public?

**Comment by iksoolim** [comment]
Thank you for your interest. The code is written in Mathematica and is primarily intended for visualization purposes, with limited focus on simulation. The paper predominantly presents analytical results. If you have specific questions about the code, feel free to reach out to me via email at i.lim@greenwich.ac.uk.
